version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entranceExam
    restart: always
    env_file: config.env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start


